lhcbpr-mysql:
  container_name: lhcbpr-mysql-dev
  extends:
    file: ../../../LHCbPR2BE/docker/dev/docker-compose.yml
    service: lhcbpr-mysql

lhcbpr-api:
  container_name: lhcbpr-api-dev
  extends:
    file: ../../../LHCbPR2BE/docker/common/docker-api.yml
    service: lhcbpr-api
  dockerfile: docker/dev/Dockerfile
  env_file:
    - ../../../LHCbPR2BE/env/dev/env-api
    - ../../../LHCbPR2BE/env/dev/env-db
  volumes:
    - ../../../LHCbPR2BE:/code
  links:
    - lhcbpr-mysql:lhcbpr-mysql
  ports:
    - "8080:80"

lhcbpr-www:
  container_name: lhcbpr-www-dev
  build: ../..
  dockerfile: docker/dev/Dockerfile
  ports:
    - "80:80"
  volumes:
    - ../../backend-angular/app:/usr/share/nginx/html/app
    - ../../nginx/conf.d:etc/nginx/conf.d
  links:
    - lhcbpr-api:lhcbpr-api
