version: '2'
services:
  lhcbpr2be:
    build:
        context: projects/LHCbPR2BE
        dockerfile: docker/Dockerfile.dev
    volumes:
        - ./data:/lhcbprdata
    env_file: projects/LHCbPR2BE/envs/default.env
    environment:
        DJANGO_HTTP_PORT: 80
    ports:
     - "8080:80" 
  lhcbpr2root:
    build:
        context: projects/LHCbPR2ROOT
        dockerfile: docker/Dockerfile.dev
    volumes:
        - ./data:/lhcbprdata
    env_file: projects/LHCbPR2BE/envs/default.env
    environment:
        DJANGO_HTTP_PORT: 80
    ports:
     - "8080:80" 
