version: '2'
services:
  lhcbpr2be:
    build:
        context: projects/LHCbPR2BE
        dockerfile: docker/Dockerfile.dev
    volumes:
        - ./var/data:/lhcbprdata
        - ./projects/LHCbPR2BE:/app
    env_file: projects/LHCbPR2BE/envs/default.env
    environment:
        DJANGO_HTTP_PORT: 80
    ports:
     - "8080:80"

  lhcbpr2root:
    build: projects/LHCbPR2ROOT
    volumes:
        - ./var/data:/lhcbprdata
        - ./projects/LHCbPR2ROOT:/app
    env_file: projects/LHCbPR2ROOT/envs/default.env
    environment:
        FLASK_PORT: 80
        ROOT_DATA: /lhcbprdata
    ports:
     - "8081:80" 

  lhcbpr2fe:
    build:
        context: projects/lhcbpr2fe
        dockerfile: docker/Dockerfile.dev
    links:
        - lhcbpr2be
        - lhcbpr2root
    environment:
        - FE_URL_API=/api
        - FE_URL_ROOT=/root
        - FE_PORT=9000
        - FE_LIVE_PORT=35729
    volumes:
        - ./projects/lhcbpr2fe:/app
    ports:
        - "9000:9000"
        - "35729:35729"
  
  lhcbpr2all:
    image: "nginx:stable-alpine"
    volumes:
        - ./docker/data/nginx:/etc/nginx
        - ./var/log/nginx:/var/log/nginx
    volumes_from:
        - lhcbpr2be
    links:
        - lhcbpr2fe
        - lhcbpr2be
        - lhcbpr2root
    ports:
        - "80:80"

 
