lhcbpr-mysql:
  image: mysql:5.5
  restart: always
  container_name: lhcbpr-mysql

  env_file: ./env-db
  ports:
    - "3306:3306"

lhcbpr-api:
  build: .
  restart: always
  container_name: lhcbpr-api
  env_file:
    - ./env-api
    - ./env-db
  links:
    - lhcbpr-mysql:lhcbpr-mysql
  ports:
    - "8080:8080"
  volumes:
    - .:/code
