version: '2'
services:
  lhcbpr2be:
    build: projects/LHCbPR2BE
    volumes:
        - ./var/data:/lhcbprdata
        - ./projects/LHCbPR2BE:/app
    env_file: projects/LHCbPR2BE/envs/default.env
    environment:
        DB_DATABASE: /lhcbprdata/lhcbpr2dev.sqlite
        DJANGO_RUN_MIGRATE: "yes"
        DJANGO_HTTP_PORT: 80
        MEDIA_ROOT: /lhcbprdata
    ports:
     - "8082:80"

  lhcbpr2root:
    build: projects/LHCbPR2ROOT
    volumes:
        - ./var/data:/lhcbprdata
        - ./projects/LHCbPR2ROOT:/app
    env_file: projects/LHCbPR2ROOT/envs/default.env
    environment:
        FLASK_PORT: 80
        DEBUG: "True"
        ROOT_DATA: /lhcbprdata/jobs
    ports:
     - "8081:80" 

  lhcbpr2fe:
    build: projects/lhcbpr2fe
    links:
        - lhcbpr2be
        - lhcbpr2root
    environment:
        - FE_URL_API=/api
        - FE_URL_ROOT=/root
        - FE_PORT=80
        - FE_LIVE_PORT=35729
    volumes:
        - ./projects/lhcbpr2fe:/app
    ports:
        - "8080:80"
  
  lhcbpr2all:
    build: .
    volumes_from:
        - lhcbpr2be:ro
    links:
        - lhcbpr2fe
        - lhcbpr2be
        - lhcbpr2root
    environment:
        APP_HOST: localhost
        APP_SECURE_LOCATION: /secure
    ports:
        - "80:80"
        - "443:443"
        - "35729:35729"

  lhcbpr2night:
    image: mazurov/cvmfs-lhcb-lhcbpr
    privileged: true
    volumes:
        - ./projects/LbNightlyTools:/app
        - ./projects/LHCbPR2HD:/LHCbPR2HD
        - ./var/data:/lhcbprdata
    environment:
        LHCBPR_HANDLERS_PATH: "/LHCbPR2HD"
        LHCBPR_API_URL: https://lblhcbpr2.cern.ch/api
        NOSSL: "true"

    

 
