version: '2'
services:
  lhcbpr2be:
    image: mazurov/lhcbpr2be
    volumes:
        - /lhcbprdata:/lhcbprdata
    environment:
        DJANGO_SERVER_TYPE: gunicorn
        DJANGO_HTTP_PORT: 80
        DJANGO_STATIC_ROOT: /html/api/static

  lhcbpr2root:
    image: mazurov/lhcbpr2root
    volumes_from:
        - lhcbpr2be:ro
    environment:
        FLASK_SERVER_TYPE: gunicorn
        FLASK_PORT: 80
        ROOT_DATA: /lhcbprdata

  lhcbpr2fe:
    image: mazurov/lhcbpr2fe
    links:
        - lhcbpr2be
        - lhcbpr2root
    environment:
        FE_DIST_DIR: /usr/share/nginx/www
        FE_SERVER_TYPE: nginx
        FE_URL_API: /api
        FE_URL_ROOT: /root
  
  lhcbpr2all:
    image: mazurov/lhcbpr2all
    volumes_from:
        - lhcbpr2be:ro
    links:
        - lhcbpr2fe
        - lhcbpr2be
        - lhcbpr2root
    environment:
        APP_SERVER_NAME: lblhcpr2.cern.ch
    ports:
        - "80:80"
        - "443:443"

 
