#!/usr/bin/env python
###############################################################################
# (c) Copyright 2013 CERN                                                     #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
'''
Run a LHCbPR job

'''
__author__ = 'Ben Couturier <ben.couturier@cern.ch>'

import LbUtils.Script
import re
import sys
from datetime import datetime
from LbPR.LbPRJobManager import JobManager
from LbNightlyTools import Configuration


def getProjectVersionFromConfig(config, project):
    ''' Look up the project version for SetupProject '''
    retval = None
    for proj in config[u'projects']:
        if proj['name'].lower() == project.lower():
            retval = proj['version']
            break
    return retval


def getSlotDateFromConfig(config):
    completed = config["completed"]
    return datetime.strptime(completed, '%Y-%m-%dT%H:%M:%S.%f')


class Script(LbUtils.Script.PlainScript):

    '''
    Script to create the commands to run a LHCbPR Job
    '''
    __usage__ = '%prog  <command> <project> <version> <platform>' \
                ' <options> <setup-options> <slot config>'
    __version__ = ''

    def defineOpts(self):
        '''Define options.'''
        from LbNightlyTools.Scripts.Common import addBasicOptions
        self.parser.add_option('-u', '--url', action='store',
                               help='URL for the LHCbPR REST service')
        self.parser.add_option('-c', '--check-ssl', action='store_true',
                               help='Check SSL certificate.')
        self.parser.add_option('-o', '--output', action='store',
                               help='output file name '
                                    '[default: runlhcbpr.sh]')
        addBasicOptions(self.parser)

    @staticmethod
    def interpretOptions(options, app_name, app_version, platform):
        if not options["executable"]:
            return options["content"]

        return options["executable"]["content"].format(
            app_name=app_name,
            app_version=app_version,
            platform=platform,
            build="build",
            options=options["content"])

    @staticmethod
    def interpretSetup(setup, app_name, app_version):
        if not setup:
            return ''

        return setup["content"].format(app_name=app_name, app_version=app_version)

    @staticmethod
    def interpretSetupArgs(setupcontent):
        if setupcontent:
            return "--setup-name='{setup[description]}' --setup-content='{setup[content]}'".format(
                setup=setupcontent)
        return ""

    @staticmethod
    def interpretExecArgs(options):
        if not options["executable"]:
            return ""
        return "--exec-name='{ex[name]}' --exec-content='{ex[content]}'".format(ex=options["executable"])

    def main(self):
        '''
        Main function of the script.
        '''

        # Checking the arguments
        if len(self.args) != 6:
            self.parser.error('Please specify <project> <version> <platform> '
                              '<options> <setup-options> <slot config>')
            exit(1)

        application = self.args[0]
        version = self.args[1]
        platform = self.args[2]
        job_options = self.args[3]

        testenv = self.args[4].split("|")
        setup_options = testenv[0]
        handlers = "TimingHandler,BrunelMemHandler"
        if len(testenv) > 1:
            handlers = testenv[1]

        slot_config = self.args[5]

        # Parsing the slot config to extract relevant information
        self.log.info("Parsing config file %s" % slot_config)
        config = Configuration.load(slot_config)
        project_version = getProjectVersionFromConfig(config, application)
        slot_completed = getSlotDateFromConfig(config)
        # print("SASHA", slot_completed)
        self.log.info("Using %s %s", application, project_version)

        # Now create the interface with LHCbPR
        manager = JobManager(self.options.url, self.options.check_ssl)
        try:
            # Get the actual options based on description
            optionscontent = manager.getJobOptions(job_options)

            # Get the actual options based on description
            setupcontent = manager.getSetupOptions(setup_options)

        except Exception as exc:
            self.log.error("Could not get job description options "
                           "from LHCbPR: %s",
                           str(exc))
            raise exc

        runfilename = "runlhcbpr.sh"
        if self.options.output != None:
            runfilename = self.options.output

        self.log.warning("Writing file: %s", runfilename)

        try:
            with open(runfilename, 'w') as runfile:
                # runfile.write("\n")
                # lblogin_cmd = ". LbLogin.sh -c %s" % platform
                setup_cmd = self.interpretSetup(
                    setup=setupcontent, app_name=application, app_version=project_version)
                run_cmd = self.interpretOptions(
                    options=optionscontent, app_name=application, app_version=project_version,
                    platform=platform)
                print(run_cmd, optionscontent)
                setup_args = self.interpretSetupArgs(setupcontent)
                exec_args = self.interpretExecArgs(optionscontent)


                runfile.write('''
#!/usr/bin/env bash
#
# File generated by lbpr-get-command to run the LHCbPR Job
#

set -v

# Setting the CMTPROJECTPATH for the software installed locally
if [ -f build/setupSearchPath.sh ]; then
   . build/setupSearchPath.sh
fi
export User_release_area=$(pwd)/build
# Setting the environment and cleanup
OLDPATH=$PATH
{setup_cmd}
rm -f start.txt end.txt platform.txt
echo $CMTCONFIG > platform.txt

# Add valgrind from AFS to the PATH
if [ -f /afs/cern.ch/lhcb/group/rich/vol4/jonrob/scripts/new-valgrind.sh ]; then
 source /afs/cern.ch/lhcb/group/rich/vol4/jonrob/scripts/new-valgrind.sh
fi

# Adding jemalloc for the perf jobs
if [ -d /opt/dirac/lhcbpr/sw/jemalloc-3.6.0/lib ]; then
  export LD_LIBRARY_PATH=/opt/dirac/lhcbpr/sw/jemalloc-3.6.0/lib:$LD_LIBRARY_PATH
fi

echo $LD_LIBRARY_PATH
# Now running the test itself
set -o pipefail
date +"%Y-%m-%d %T %z" > start.txt
{run_cmd} | tee run.log
PATH=$OLDPATH

RETCODE=$?
date +"%Y-%m-%d %T %z" > end.txt
echo "==> Return code: $RETCODE"
# Gathering the results with LHCbPR

if [ "$RETCODE" = "0" ] ; then
    echo "Run OK now gathering the results"
    lbpr-collect -s "`cat start.txt`" -e "`cat end.txt`" -p `hostname` -c `cat platform.txt` --opt-content='{options[content]}' {setup_args} {exec_args} --opt-name='{options[description]}' -l '{handlers}' --app-name='{app_name}' --app-version='{app_version}'  --app-version-datetime="{app_version_datetime}" -a
else
    echo "Non 0 return code - Will NOT gather the results and push to LHCbPR"
fi

exit $RETCODE
                '''.format(setup_cmd=setup_cmd, run_cmd=run_cmd, options=optionscontent, setup_args=setup_args, exec_args=exec_args, handlers=handlers, app_name=application, app_version=version, app_version_datetime=slot_completed.strftime("%Y-%m-%d %H:%M:%S -0400")))
        except Exception as exc:
            self.log.error("Error generating runfile: %s",
                           str(exc))
            raise exc

# __main__
sys.exit(Script().run())
