#!/usr/bin/env python
###############################################################################
# (c) Copyright 2013 CERN                                                     #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
'''
Synchronize the dashboard with the content of the artifacts directory.
'''

import sys
import os
import urllib

from LbNightlyTools.Utils import Dashboard

from datetime import datetime

import LbUtils.Script
class Script(LbUtils.Script.PlainScript):
    '''
    Synchronize the content of the Dashboard with the artifacts directories.
    '''
    __usage__ = '%prog [options] [day ...]'

    def main(self):
        '''
        Script logic.
        '''
        dash = Dashboard()

        if self.args:
            days = self.args
        else:
            days = [None] # use the default day

        if os.path.exists(dash.ARTIFACTS_ROOT):
            for day in days:
                dash.publishFromArtifacts(day)
        else:
            self.log.warning('cannot find directory %s', dash.ARTIFACTS_ROOT)

        return 0

if __name__ == '__main__':
    sys.exit(Script().run())
