#!/usr/bin/env python
###############################################################################
# (c) Copyright 2013 CERN                                                     #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
'''
Parse the build parameters specified in the test environment variable
'''
__author__ = 'Ben Couturier <ben.couturier@cern.ch>'
import os
from LbNightlyTools.Utils import JenkinsTest

teststr = os.environ['test']
if teststr and teststr != 'default':
    test = JenkinsTest.fromJenkinsString(teststr)
    open('parameters.txt', 'w').writelines(test.getParameterLines())
    open('os_label.txt', 'w').write('os_label=%s\n' % test.os_label)