#!/usr/bin/env python
###############################################################################
# (c) Copyright 2015 CERN                                                     #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
'''
Script to convert a console output to html.
'''

import os
from LbNightlyTools.HTMLUtils import XTerm2HTML
from optparse import OptionParser

parser = OptionParser(usage='%prog [options] <input> <output>')

try:
    opts, (input, output) = parser.parse_args()
except ValueError:
    parser.error('wrong number of arguments')

conv = XTerm2HTML()
with open(output, 'w') as dest, open(input) as src:
    dest.write(conv.head(title=os.path.basename(input)))
    dest.write(conv.process(src.read()))
    dest.write(conv.tail())
