#!/usr/bin/env python
###############################################################################
# (c) Copyright 2013 CERN                                                     #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
'''
Publish to the dashboard disk usage statistics for all the directories specified
on the command line.
'''

import sys
import os
import urllib
import logging

logging.basicConfig()

from LbNightlyTools.Monitoring import getDirInfos
from LbNightlyTools.Utils import Dashboard

dash = Dashboard()
for path in set([os.path.realpath(p) for p in sys.argv[1:]]):
    name = urllib.quote(path, safe='')
    data = getDirInfos(path)
    data['type'] = 'disk-usage'
    dash.publish(data, name=name)
