#!/usr/bin/env bash

BASEDIR=$(dirname "$0")
# export JENKINS_MOCK=true
# export ARTIFACTS_DIR=build
export lhcbpr_api_url="https://prl-dev/api"
export lhcbpr_check_ssl="false"

export testenv='|GeantStandaloneHandler'
export testgroup='GEANT_RUNHADRONIC'
export testrunner=lhcbpr
export slot=lhcb-gauss-dev
export slot_build_id=883
# export slot=lhcb-gauss-cmake
# export slot_build_id=9
# export slot=lhcb-g4r10
# export slot_build_id=113
export platform=x86_64-slc6-gcc48-opt
export project=Geant4
export input_flavour=nightly
export flavour=periodic
export os_label=perf
#$BASEDIR/../jenkins/mock.sh nightly-slot-test-project-platform2 lhcb-gauss-dev  x86_64-slc6-gcc48-opt Geant4
$BASEDIR/../jenkins/nightly-slot-test-project-platform2.sh
