# Macros and functions used by the test driver

macro(gen_projects_xml)
  set(data "<Project name=\"${slot}\">")
  foreach(p ${projects})
    set(data "${data}\n  <SubProject name=\"${p}\">")
    foreach(d ${${p}_dependencies})
      set(data "${data}\n    <Dependency name=\"${d}\"/>")
    endforeach()
    set(data "${data}\n  </SubProject>")
  endforeach()
  set(data "${data}\n</Project>\n")
  file(WRITE "${SLOT_BUILD_DIR}/Project.xml" "${data}")
endmacro()

macro(get_deps output)
  foreach(name ${ARGN})
    get_deps(${output} ${${name}_dependencies})
    set(${output} ${${output}} ${name})
  endforeach()
  if(${output})
    list(REMOVE_DUPLICATES ${output})
  endif()
endmacro()

macro(sort_projects)
  set(sorted_projects)
  get_deps(sorted_projects ${projects})
  set(projects ${sorted_projects})
endmacro()

macro(load_config)
  message(STATUS "Loading slot configuration.")
  include(SlotConfig)
  sort_projects()
  message(STATUS "Building ${slot} for ${config}.")
endmacro()

macro(prepare_build_dir)
  message(STATUS "Preparing sources.")
  file(GLOB sources "sources/*.tar.bz2")
  if(sources)
    execute_process(COMMAND rm -rf ${SLOT_BUILD_DIR})
    file(MAKE_DIRECTORY ${SLOT_BUILD_DIR})
    foreach(source ${sources})
      message(STATUS "  unpacking ${source}")
      execute_process(COMMAND tar xf ${source}
                      WORKING_DIRECTORY ${SLOT_BUILD_DIR})
    endforeach()
  else()
    message(FATAL_ERROR "No source tarball found: nothing to build.")
  endif()
endmacro()
